name: Sync CopenhagenTheme Content to Main

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:38 and 12:38 UTC every day
    - cron: '38 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/copenlight
        clean: true
        persist-credentials: true

    - name: Reset Git remote
      run: |
        git remote remove origin || true
        git remote add origin https://github.com/ivancarlosti/copenlight.git
        git remote -v

    - name: Download CopenhagenTheme content from main
      run: |
        mkdir -p /tmp/copenhagen_temp
        cd /tmp/copenhagen_temp
        git clone --branch main --depth 1 https://github.com/zendesk/copenhagen_theme.git
        echo "== Checking manifest.json version =="

        if [ ! -f copenhagen_theme/manifest.json ]; then
          echo "No manifest.json file found, aborting sync."
          exit 0
        fi

        VERSION=$(jq -r '.version // empty' copenhagen_theme/manifest.json)
        if [ -z "$VERSION" ]; then
          echo "No version defined in manifest.json, aborting sync."
          exit 0
        fi

        if echo "$VERSION" | grep -i 'beta'; then
          echo "Version is beta ($VERSION), aborting sync."
          exit 0
        fi

        echo "Version is $VERSION. Proceeding with sync."

        rsync -av \
          --exclude='.github' \
          --exclude='.git' \
          copenhagen_theme/ "$GITHUB_WORKSPACE/"

    - name: Modify manifest.json
      run: |
        echo "== Updating manifest.json with custom name and author =="
        MANIFEST="$GITHUB_WORKSPACE/manifest.json"
        if [ -f "$MANIFEST" ]; then
          jq '.name = "CopenLight" | .author = "Ivan Carlos"' "$MANIFEST" > "$MANIFEST.tmp" && mv "$MANIFEST.tmp" "$MANIFEST"
        else
          echo "manifest.json not found!"
          exit 1
        fi

    - name: Append custom CSS to style.css
      run: |
        echo "== Appending custom CSS rules to style.css =="
        STYLE_CSS="$GITHUB_WORKSPACE/style.css"
        if [ -f "$STYLE_CSS" ]; then
          {
            echo ""
            echo "/* ### BEGIN part to remove section */"
            echo ".recent-activity-item-comment {"
            echo "  display: none;"
            echo "}"
            echo ".article-votes {"
            echo "  display: none;"
            echo "}"
            echo ".share {"
            echo "  display: none;"
            echo "}"
            echo ".comment-overview {"
            echo "  display: none;"
            echo "}"
            echo ".comment-callout {"
            echo "  display: none;"
            echo "}"
            echo "/* ### END part to remove section */"
          } >> "$STYLE_CSS"
        else
          echo "style.css not found!"
          exit 1
        fi

    - name: Cleanup temp files
      run: |
        rm -rf /tmp/copenhagen_temp
        echo "Temp folder cleaned."

    - name: Commit changes
      run: |
        cd "$GITHUB_WORKSPACE"
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .

        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Sync CopenhagenTheme content [▶️] - version $VERSION"
        else
          echo "No changes to commit"
          exit 0
        fi

    - name: Push changes
      run: |
        cd "$GITHUB_WORKSPACE"
        git push \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/ivancarlosti/copenlight.git \
          HEAD:main
        echo "Push successful"
