name: Sync CopenhagenTheme Repository

on:
  workflow_dispatch:
  schedule:
    - cron: '38 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/copenlight
        clean: true
        persist-credentials: true

    - name: Reset Git remote
      run: |
        git remote remove origin || true
        git remote add origin https://github.com/ivancarlosti/copenlight.git
        git remote -v

    - name: Download CopenhagenTheme content (from master)
      run: |
        mkdir -p /tmp/copenhagen_temp
        cd /tmp/copenhagen_temp
        git clone --branch master https://github.com/zendesk/copenhagen_theme.git
        echo "== Checking manifest.json version =="

        MANIFEST="/tmp/copenhagen_temp/copenhagen_theme/manifest.json"
        if [ ! -f "$MANIFEST" ]; then
          echo "No manifest.json file found, aborting sync."
          exit 0
        fi

        cat "$MANIFEST"
        VERSION=$(jq -r '.version // empty' "$MANIFEST")

        if [ -z "$VERSION" ]; then
          echo "No version defined in manifest.json, aborting sync."
          exit 0
        fi

        if echo "$VERSION" | grep -i 'beta'; then
          echo "Version is beta ($VERSION), aborting sync."
          exit 0
        fi

        echo "Version is $VERSION. Proceeding with sync."

        rsync -av \
          --exclude='.github' \
          --exclude='.git' \
          --exclude='README.md' \
          --exclude='LICENSE' \
          /tmp/copenhagen_temp/copenhagen_theme/ "$GITHUB_WORKSPACE/"

    - name: Debug manifest.json in workspace
      run: |
        echo "=== manifest.json in your repo after sync ==="
        cat "$GITHUB_WORKSPACE/manifest.json" || echo "manifest.json missing!"

    - name: Modify manifest.json
      run: |
        echo "== Updating manifest.json with custom name and author =="
        MANIFEST="$GITHUB_WORKSPACE/manifest.json"
        if [ -f "$MANIFEST" ]; then
          jq '.name = "CopenLight" | .author = "Ivan Carlos"' "$MANIFEST" > "$MANIFEST.tmp" && mv "$MANIFEST.tmp" "$MANIFEST"
          echo "Updated manifest.json:"
          cat "$MANIFEST"
        else
          echo "manifest.json not found!"
          exit 1
        fi

    - name: Append custom CSS to style.css
      run: |
        echo "== Appending custom CSS rules to style.css =="
        STYLE_CSS="$GITHUB_WORKSPACE/style.css"
        if [ -f "$STYLE_CSS" ]; then
          {
            echo ""
            echo "/* ### BEGIN part to custom style */"
            echo ".recent-activity-item-comment { display: none; }"
            echo ".article-votes { display: none; }"
            echo ".share { display: none; }"
            echo ".comment-overview { display: none; }"
            echo ".comment-callout { display: none; }"
            echo ""
            echo "/* ===== Container da página do artigo ===== */"
            echo ".article-container, #article-container {"
            echo "  display: flex !important;"
            echo "  flex-wrap: wrap !important;"
            echo "  justify-content: center !important;"
            echo "  align-items: flex-start !important;"
            echo "  max-width: 1300px !important;"
            echo "  margin: 0 auto !important;"
            echo "  padding: 0 16px !important;"
            echo "  box-sizing: border-box !important;"
            echo "  background: transparent !important;"
            echo "  gap: 40px !important;"
            echo "  width: 100% !important;"
            echo "}"
            echo ""
            echo "/* ===== Artigo principal ===== */"
            echo "#main-content.article, .article, .article-body, #article-body {"
            echo "  flex: 1 1 700px !important;"
            echo "  max-width: 900px !important;"
            echo "  min-width: 300px !important;"
            echo "  width: 100% !important;"
            echo "  background: #fff !important;"
            echo "  padding: 40px 36px !important;"
            echo "  border-radius: 12px !important;"
            echo "  box-shadow: 0 6px 24px rgb(0 0 0 / 0.10) !important;"
            echo "  margin: 40px 0 !important;"
            echo "  font-size: 18px !important;"
            echo "  line-height: 1.7 !important;"
            echo "  box-sizing: border-box !important;"
            echo "  overflow-x: auto !important;"
            echo "}"
            echo ""
            echo "/* ===== Sidebar lateral ===== */"
            echo ".zd-sidebar, .article-sidebar {"
            echo "  flex: 0 0 260px !important;"
            echo "  max-width: 260px !important;"
            echo "  width: 100% !important;"
            echo "  background: #f1f5f9 !important;"
            echo "  padding: 20px !important;"
            echo "  border-radius: 10px !important;"
            echo "  box-shadow: 0 2px 8px rgb(0 0 0 / 0.05) !important;"
            echo "  font-size: 15px !important;"
            echo "  line-height: 1.5 !important;"
            echo "  margin: 40px 0 !important;"
            echo "  box-sizing: border-box !important;"
            echo "}"
            echo ""
            echo "/* ===== Responsividade ===== */"
            echo "@media (max-width: 1150px) {"
            echo "  .article-container, #article-container {"
            echo "    flex-direction: column !important;"
            echo "    gap: 0 !important;"
            echo "    max-width: 100% !important;"
            echo "    padding: 0 6vw !important;"
            echo "  }"
            echo "  #main-content.article, .article, .article-body, #article-body {"
            echo "    max-width: 100% !important;"
            echo "    padding: 18px 1vw !important;"
            echo "    margin: 10px 0 !important;"
            echo "    border-radius: 8px !important;"
            echo "    font-size: 16px !important;"
            echo "  }"
            echo "  .zd-sidebar, .article-sidebar {"
            echo "    max-width: 100% !important;"
            echo "    margin: 0 0 24px 0 !important;"
            echo "    border-radius: 8px !important;"
            echo "  }"
            echo "}"
            echo ""
            echo "/* ===== Evita scroll horizontal da página ===== */"
            echo "html, body {"
            echo "  overflow-x: hidden !important;"
            echo "}"
            echo ""
            echo "/* ===== Estilos gerais ===== */"
            echo "body {"
            echo "  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif !important;"
            echo "  background: #fafafa !important;"
            echo "  color: #222 !important;"
            echo "  margin: 0 !important;"
            echo "}"
            echo ""
            echo "h1, h2, h3, h4 {"
            echo "  color: #004080 !important;"
            echo "  font-weight: 700 !important;"
            echo "  margin-top: 1.5em !important;"
            echo "  margin-bottom: 0.5em !important;"
            echo "}"
            echo ""
            echo "a {"
            echo "  color: #007acc !important;"
            echo "  text-decoration: none !important;"
            echo "  transition: color 0.3s ease !important;"
            echo "}"
            echo "a:hover, a:focus {"
            echo "  color: #005a99 !important;"
            echo "  text-decoration: underline !important;"
            echo "}"
            echo ""
            echo "p {"
            echo "  margin-bottom: 1.15em !important;"
            echo "  font-size: 18px !important;"
            echo "}"
            echo ""
            echo "ul, ol {"
            echo "  margin-left: 1.7em !important;"
            echo "  margin-bottom: 1.1em !important;"
            echo "  font-size: 17px !important;"
            echo "}"
            echo ""
            echo "ul li strong {"
            echo "  color: #d9534f !important;"
            echo "}"
            echo ""
            echo "table {"
            echo "  border-collapse: collapse !important;"
            echo "  width: 100% !important;"
            echo "  margin-bottom: 1.5em !important;"
            echo "}"
            echo ""
            echo "th, td {"
            echo "  border: 1px solid #ddd !important;"
            echo "  padding: 10px !important;"
            echo "  text-align: left !important;"
            echo "}"
            echo ""
            echo "th {"
            echo "  background-color: #007acc !important;"
            echo "  color: white !important;"
            echo "}"
            echo ""
            echo "img, .article-body img {"
            echo "  max-width: 100% !important;"
            echo "  height: auto !important;"
            echo "  border-radius: 7px !important;"
            echo "  box-shadow: 0 2px 10px rgb(0 0 0 / 0.1) !important;"
            echo "  margin: 1.5em 0 !important;"
            echo "}"
            echo ""
            echo "/* ===== Estilos para blocos <pre> simples com numeração e botão copiar ===== */"
            echo "pre {"
            echo "  position: relative !important;"
            echo "  background: #f7f9fc !important;"
            echo "  border-left: 5px solid #007acc !important;"
            echo "  padding: 17px 45px 17px 50px !important; /* espaço para coluna de números */"
            echo "  border-radius: 5px !important;"
            echo "  margin-bottom: 2em !important;"
            echo "  box-shadow: 0 2px 10px rgb(0 0 0 / 0.10) !important;"
            echo "  font-family: Consolas, Monaco, 'Courier New', monospace !important;"
            echo "  font-size: 16px !important;"
            echo "  line-height: 1.6 !important;"
            echo "  overflow-x: auto !important;"
            echo "  white-space: pre !important;"
            echo "}"
            echo ""
            echo "/* Coluna dos números das linhas dentro do <pre> */"
            echo "pre .line-number {"
            echo "  position: absolute !important;"
            echo "  top: 17px !important;"
            echo "  left: 10px !important;"
            echo "  color: #b0b0b0 !important;"
            echo "  text-align: right !important;"
            echo "  width: 30px !important;"
            echo "  user-select: none !important;"
            echo "  font-family: "Courier New", monospace !important;"
            echo "  pointer-events: none !important;"
            echo "  line-height: 1.6 !important;"
            echo "  font-size: 15px !important;"
            echo "}"
            echo ""
            echo "/* Botão copiar dentro do <pre> */"
            echo "pre .copy-btn {"
            echo "  position: absolute !important;"
            echo "  top: 17px !important;"
            echo "  right: 15px !important;"
            echo "  background: #007acc !important;"
            echo "  color: #fff !important;"
            echo "  border: none !important;"
            echo "  border-radius: 3px !important;"
            echo "  padding: 6px 15px !important;"
            echo "  font-size: 14px !important;"
            echo "  cursor: pointer !important;"
            echo "  z-index: 2 !important;"
            echo "  transition: background 0.3s !important;"
            echo "  box-shadow: 0 2px 4px rgb(0 0 0 / 0.07) !important;"
            echo "}"
            echo ""
            echo "pre .copy-btn:hover {"
            echo "  background: #005a99 !important;"
            echo "}"
            echo ""
            echo ""
            echo ""
            echo "/* ===== Responsividade para pequenos dispositivos ===== */"
            echo "@media (max-width: 900px) {"
            echo "  #main-content.article, .article, .article-body, #article-body {"
            echo "    padding: 10px 2vw !important;"
            echo "    font-size: 16px !important;"
            echo "  }"
            echo "  pre {"
            echo "    padding-left: 38px !important;"
            echo "    font-size: 15px !important;"
            echo "  }"
            echo "  pre .copy-btn {"
            echo "    top: 8px !important;"
            echo "    right: 8px !important;"
            echo "    padding: 6px 12px !important;"
            echo "    font-size: 13px !important;"
            echo "  }"
            echo "}"
            echo "/* ### END part to custom style */"
          } >> "$STYLE_CSS"
          echo "CSS rules appended to style.css"
        else
          echo "style.css not found!"
          exit 1
        fi

- name: Append custom JS to script.js
  run: |
    echo "== Appending custom JS rules to script.js =="
    SCRIPT_JS="$GITHUB_WORKSPACE/script.js"
    if [ -f "$SCRIPT_JS" ]; then
      cat <<'EOF' >> "$SCRIPT_JS"

    // ### BEGIN part to custom JS

    document.addEventListener("DOMContentLoaded", function() {
      document.querySelectorAll('pre').forEach(function(pre) {
        // Evita duplicar a numeração se já existir
        if (pre.querySelector('.line-number')) return;

        const lines = pre.textContent.split('\n');
        const lineNumbersHtml = lines.map((_, i) => `<span>${i + 1}</span>`).join('<br>');
        const lineNumberDiv = document.createElement('div');
        lineNumberDiv.className = 'line-number';
        lineNumberDiv.innerHTML = lineNumbersHtml;

        pre.style.position = 'relative'; // necessário para posicionar os números e botão

        pre.insertBefore(lineNumberDiv, pre.firstChild);

        // Criar e adicionar botão copiar
        const copyBtn = document.createElement('button');
        copyBtn.className = 'copy-btn';
        copyBtn.type = 'button';
        copyBtn.textContent = 'Copiar';

        copyBtn.addEventListener('click', function() {
          navigator.clipboard.writeText(pre.innerText).then(() => {
            copyBtn.textContent = 'Copiado!';
            setTimeout(() => { copyBtn.textContent = 'Copiar'; }, 1500);
          }).catch(() => {
            copyBtn.textContent = 'Erro';
            setTimeout(() => { copyBtn.textContent = 'Copiar'; }, 1500);
          });
        });

        pre.appendChild(copyBtn);
      });
    });

    // ### END part to custom JS

EOF
      echo "JS rules appended to script.js"
    else
      echo "script.js not found!"
      exit 1
    fi


    - name: Cleanup temp files
      run: rm -rf /tmp/copenhagen_temp

    - name: Commit changes
      run: |
        cd "$GITHUB_WORKSPACE"
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .

        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Sync CopenhagenTheme content [▶️]"
          echo "Commit created"
        fi

    - name: Push changes
      run: |
        cd "$GITHUB_WORKSPACE"
        git push \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/ivancarlosti/copenlight.git \
          HEAD:main
        echo "Push successful"
